### ISSUE TITLE
v0.0.7 Blue Screen

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge-nr-dashboard#107]
### Description

When installing v0.0.7 via the Palette Manager, it does not connect to Node-RED. These are the Node-RED logs:

```sh
05/08/2023 18:15:43 [info] Stopped flows
05/08/2023 18:15:43 [info] Updated flows
05/08/2023 18:15:43 [info] Starting flows
05/08/2023 18:15:43 [] queueing emitConfig
05/08/2023 18:15:43 [info] UI Page Constructor
05/08/2023 18:15:43 [info] UI Page Constructor
05/08/2023 18:15:43 [info] Started flows
05/08/2023 18:15:43 [] emitting config to 0 connections
```

and this is shown in the browser console:

```
polling.js:298     GET http://localhost:12082/ui/socket.io/?EIO=4&transport=polling&t=Od6jBde 404 (Not Found)
create @ polling.js:298
re @ polling.js:237
request @ polling.js:190
doPoll @ polling.js:215
poll @ polling.js:96
doOpen @ polling.js:56
open @ transport.js:46
open @ socket.js:168
be @ socket.js:109
open @ manager.js:108
(anonymous) @ manager.js:328
main.js:66 SIO connect error: Error: xhr poll error
    at ne.onError (transport.js:38:37)
    at re.<anonymous> (polling.js:218:18)
    at F.emit (index.mjs:136:20)
    at re.onError (polling.js:320:14)
    at polling.js:294:30 undefined
```

Note that a connection is never made, which would indicate an issue with the new event architecture/connection work. 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Just noticed the connection for sockets is trying to connect to: `/ui/socket.io`.

Code creating this connection is:

```js
const fullPath = join(RED.settings.httpNodeRoot, config.path)
const socketIoPath = join('/', fullPath, 'socket.io')
/** @type {import('socket.io/dist').ServerOptions} */
const serverOptions = {
    path: socketIoPath
}
console.log('Creating socket.io server at path', socketIoPath)
// store reference to the SocketIO Server
ui.ioServer = new Server(ui.httpServer, serverOptions)
```

so it _should_ be getting the right value. Although, thinking out loud, should it in fact be reading `node.path`, not `config.path`? It's weird though as there are no instances of `/ui` as a path anywhere in our source code, but the base node is _definitely_ returning `/ui` as it's path value, even on a fresh install (via FlowForge, or as shown in the [Discourse post](https://discourse.nodered.org/t/dashboard-2-0-pre-alpha-available/80142/48?u=joepavitt))

**Comment by joepavitt** [comment]
Just had a realisation for what the problem is. I was looking server side for instances of `/ui`, but the problem is actually client-side, where it isn't going to be aware of the server side config in order to get the base URL of the UI in the first place...

So, we need to have a fixed URL path defined that the socket.io connection links to, such that the UI and Server have an agreed point of connection, before any configuration is passed.

We know `/ui` is taken by Dashboard 1.0, but having a `/dashboard-2` endpoint just for all socket connections feels reasonable. 

Would appreciate thoughts on this @Steve-Mcl

**Comment by joepavitt** [comment]
Short term fix to unlock `main` is set the socket client to point to `/dashboard`
