### ISSUE TITLE
Url redirect, refresh and crash 

### ISSUE THREAD

**Issue by E1cid** [flowforge/flowforge-nr-dashboard#87]
Installed new pre alpha dashboard using pallete.

Created a page with text node. Did not change /ui.
Opened OG dashboard, redirected to new ui page. Went back change /ui to /dash.

Opening old dashboard redirect to new ...180/dash/ui-testing.
If i refreshed the page receive `can not get /dash/ui-testing`.

So removed the node and all unused configs.
Refreshed editor.
Opening Old dasboad url, redirects to /dash/... and shows text input box etc. The text input node was deleted and deployed.

So went to remove the alpha dash in pallette but says inuse, no nodes in any tabs or configs etc.

Then node-red crashed
[details="Log"]
```
Jul 18:41:10 - [info] Added node types:
28 Jul 18:41:10 - [info]  - @flowforge/node-red-dashboard:ui-base
28 Jul 18:41:10 - [info]  - @flowforge/node-red-dashboard:ui-page
28 Jul 18:41:10 - [info]  - @flowforge/node-red-dashboard:ui-group
28 Jul 18:41:10 - [info]  - @flowforge/node-red-dashboard:ui-theme
28 Jul 18:41:10 - [info]  - @flowforge/node-red-dashboard:ui-text-input
28 Jul 18:41:10 - [info]  - @flowforge/node-red-dashboard:ui-button
28 Jul 18:41:10 - [info]  - @flowforge/node-red-dashboard:ui-dropdown
28 Jul 18:41:10 - [info]  - @flowforge/node-red-dashboard:ui-slider
28 Jul 18:41:10 - [info]  - @flowforge/node-red-dashboard:ui-text
28 Jul 18:41:10 - [info]  - @flowforge/node-red-dashboard:ui-chart
28 Jul 18:41:10 - [info]  - @flowforge/node-red-dashboard:ui-markdown
28 Jul 18:50:49 - [info] Stopping modified nodes
28 Jul 18:50:49 - [info] Stopped modified nodes
28 Jul 18:50:49 - [info] Updated flows
28 Jul 18:50:49 - [info] Starting modified nodes
28 Jul 18:50:49 - [info] [ui-base:New Dash] Created socket.io server bound to Node-RED port at path /ui/socket.io
28 Jul 18:50:49 - [info] [ui-page:Testing] UI Page Constructor
28 Jul 18:50:49 - [info] [ui-group:One] UI Page Constructor
28 Jul 18:50:49 - [info] Started modified nodes
28 Jul 18:51:42 - [info] Stopping modified nodes
28 Jul 18:51:42 - [info] Stopped modified nodes
28 Jul 18:51:42 - [info] Updated flows
28 Jul 18:51:42 - [info] Starting modified nodes
28 Jul 18:51:42 - [info] Started modified nodes
conn:AciLPjbT4QB_6ZRjAABz on:widget-load:71f41e5a36eeaed3 undefined
conn:AciLPjbT4QB_6ZRjAABz on:widget-change qq
conn:qSqCk3GJROMYQ4iNAAB3 on:widget-load:71f41e5a36eeaed3 { payload: 'qq', _msgid: 'f931fab8272485c6' }
28 Jul 18:53:37 - [info] Stopping modified nodes
Node-RED Closed 71f41e5a36eeaed3
28 Jul 18:53:37 - [info] Stopped modified nodes
28 Jul 18:53:37 - [info] Updated flows
28 Jul 18:53:37 - [info] Starting modified nodes
28 Jul 18:53:37 - [info] [ui-page:Testing] UI Page Constructor
28 Jul 18:53:37 - [info] [ui-group:One] UI Page Constructor
28 Jul 18:53:37 - [info] Started modified nodes
28 Jul 18:53:47 - [info] [ui-base:New Dash] Disconnected kG_Ox40tuZAPmOCZAABx due to transport close
28 Jul 18:53:47 - [info] [ui-base:New Dash] Disconnected AciLPjbT4QB_6ZRjAABz due to transport close
28 Jul 18:53:52 - [info] [ui-base:New Dash] Disconnected YivtimJ1mQ1Gqx9YAAB1 due to transport error
28 Jul 18:53:52 - [info] [ui-base:New Dash] Disconnected qSqCk3GJROMYQ4iNAAB3 due to transport error
conn:YlwE-spqVId_xZZNAAB7 on:widget-load:71f41e5a36eeaed3 undefined
28 Jul 18:54:24 - [info] [ui-base:New Dash] Disconnected Z0GLwyyfptwjVVo2AAB5 due to transport close
28 Jul 18:54:24 - [info] [ui-base:New Dash] Disconnected YlwE-spqVId_xZZNAAB7 due to transport close
conn:doC5mQg8SuphdbghAAB_ on:widget-load:71f41e5a36eeaed3 undefined
28 Jul 18:56:04 - [info] Stopping modified nodes
28 Jul 18:56:04 - [info] Stopped modified nodes
28 Jul 18:56:04 - [info] Updated flows
28 Jul 18:56:04 - [info] Starting modified nodes
28 Jul 18:56:04 - [info] Started modified nodes
28 Jul 18:56:14 - [info] [ui-base:New Dash] Disconnected PGiz2mrw0wO_F_eOAAB9 due to transport close
28 Jul 18:56:14 - [info] [ui-base:New Dash] Disconnected doC5mQg8SuphdbghAAB_ due to transport close
conn:ADJpnichW8J1g3ELAACD on:widget-load:71f41e5a36eeaed3 undefined
conn:ADJpnichW8J1g3ELAACD on:widget-change null
conn:ADJpnichW8J1g3ELAACD on:widget-change null
28 Jul 18:59:24 - [info] [ui-base:New Dash] Disconnected dpOC3pythEIXbQziAACB due to transport error
28 Jul 18:59:24 - [info] [ui-base:New Dash] Disconnected ADJpnichW8J1g3ELAACD due to transport error
28 Jul 19:03:19 - [info] Stopping modified nodes
Node-RED Closed 71f41e5a36eeaed3
28 Jul 19:03:19 - [info] Stopped modified nodes
28 Jul 19:03:19 - [info] Updated flows
28 Jul 19:03:19 - [info] Starting modified nodes
28 Jul 19:03:19 - [info] Started modified nodes
28 Jul 19:03:33 - [info] Stopping modified nodes
28 Jul 19:03:33 - [info] Stopped modified nodes
28 Jul 19:03:33 - [info] Updated flows
28 Jul 19:03:34 - [info] Starting modified nodes
28 Jul 19:03:34 - [info] Started modified nodes
28 Jul 19:06:53 - [red] Uncaught Exception:
28 Jul 19:06:53 - [error] TypeError: Cannot read properties of null (reading '_msg')
    at Socket.handler (/data/data/com.termux/files/home/.node-red/node_modules/@flowforge/node-red-dashboard/nodes/config/ui_base.js:275:93)
    at Socket.emit (node:events:511:28)
    at Socket.emitUntyped (/data/data/com.termux/files/home/.node-red/node_modules/socket.io/dist/typed-events.js:69:22)
    at /data/data/com.termux/files/home/.node-red/node_modules/socket.io/dist/socket.js:703:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```
[/details]

Testing on termux android box nodejs 20, nod-red 3.0.2.
Found 2 configs Theme and base, deleted them, then was able to disable in pallette.
Will look again when next release version.

**Comment by joepavitt** [comment]
This has been fixed (temporarily) by changing the default endpoint for Dashboard 2.0 to now be at `/dashboard` rather than `/ui` and preventing this from being changed (temporarily), whilst we figure out a better solution for managing routes _alongside_ Dashboard 1.0.

The default URL was changed in https://github.com/flowforge/flowforge-nr-dashboard/pull/100
